//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persona()
        {
            this.Discapacidad = new HashSet<Discapacidad>();
            this.Matricula = new HashSet<Matricula>();
        }
    
        public string per_identificacion { get; set; }
        public string per_tipoidentificacion { get; set; }
        public string per_apellidos { get; set; }
        public string per_nombres { get; set; }
        public System.DateTime per_fechanacimiento { get; set; }
        public string per_direccion { get; set; }
        public string per_telefono { get; set; }
        public string per_celular { get; set; }
        public string per_tiposangre { get; set; }
        public string per_correo { get; set; }
        public string per_genero { get; set; }
        public string per_status { get; set; }
        public System.DateTime per_add { get; set; }
        public Nullable<System.DateTime> per_update { get; set; }
        public Nullable<System.DateTime> per_delete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Discapacidad> Discapacidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Matricula> Matricula { get; set; }
    }
}
