//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Smtp
    {
        public int smtp_codigo { get; set; }
        public string smtp_servidor { get; set; }
        public Nullable<int> smtp_puerto { get; set; }
        public string smtp_username { get; set; }
        public string smtp_password { get; set; }
        public Nullable<bool> smtp_tls { get; set; }
        public string smtp_status { get; set; }
        public Nullable<System.DateTime> smtp_add { get; set; }
    }
}
