//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int usu_id { get; set; }
        public string usu_correo { get; set; }
        public string usu_password { get; set; }
        public string usu_apellidos { get; set; }
        public string usu_nombres { get; set; }
        public string usu_status { get; set; }
        public System.DateTime usu_add { get; set; }
        public Nullable<System.DateTime> usu_update { get; set; }
        public Nullable<System.DateTime> usu_delete { get; set; }
        public Nullable<int> rol_id { get; set; }
    
        public virtual Rol Rol { get; set; }
    }
}
