#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.ClassLibrary
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DBMANTENIMIENTO")]
	public partial class DcMantenimientoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertCATEGORIA(CATEGORIA instance);
    partial void UpdateCATEGORIA(CATEGORIA instance);
    partial void DeleteCATEGORIA(CATEGORIA instance);
    partial void InsertVEHICULO(VEHICULO instance);
    partial void UpdateVEHICULO(VEHICULO instance);
    partial void DeleteVEHICULO(VEHICULO instance);
    partial void InsertCLIENTE(CLIENTE instance);
    partial void UpdateCLIENTE(CLIENTE instance);
    partial void DeleteCLIENTE(CLIENTE instance);
    partial void InsertDETALL_SERVICIO(DETALL_SERVICIO instance);
    partial void UpdateDETALL_SERVICIO(DETALL_SERVICIO instance);
    partial void DeleteDETALL_SERVICIO(DETALL_SERVICIO instance);
    partial void InsertDETALLE_ORDEN(DETALLE_ORDEN instance);
    partial void UpdateDETALLE_ORDEN(DETALLE_ORDEN instance);
    partial void DeleteDETALLE_ORDEN(DETALLE_ORDEN instance);
    partial void InsertMARCA(MARCA instance);
    partial void UpdateMARCA(MARCA instance);
    partial void DeleteMARCA(MARCA instance);
    partial void InsertMODELO(MODELO instance);
    partial void UpdateMODELO(MODELO instance);
    partial void DeleteMODELO(MODELO instance);
    partial void InsertORDEN(ORDEN instance);
    partial void UpdateORDEN(ORDEN instance);
    partial void DeleteORDEN(ORDEN instance);
    partial void InsertPRODUCTO(PRODUCTO instance);
    partial void UpdatePRODUCTO(PRODUCTO instance);
    partial void DeletePRODUCTO(PRODUCTO instance);
    partial void InsertRESERVA(RESERVA instance);
    partial void UpdateRESERVA(RESERVA instance);
    partial void DeleteRESERVA(RESERVA instance);
    partial void InsertROL(ROL instance);
    partial void UpdateROL(ROL instance);
    partial void DeleteROL(ROL instance);
    partial void InsertSERVICIO(SERVICIO instance);
    partial void UpdateSERVICIO(SERVICIO instance);
    partial void DeleteSERVICIO(SERVICIO instance);
    partial void InsertUSUARIO(USUARIO instance);
    partial void UpdateUSUARIO(USUARIO instance);
    partial void DeleteUSUARIO(USUARIO instance);
    #endregion
		
		public DcMantenimientoDataContext() : 
				base(global::AccesoDatos.ClassLibrary.Properties.Settings.Default.DBMANTENIMIENTOConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DcMantenimientoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DcMantenimientoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DcMantenimientoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DcMantenimientoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CATEGORIA> CATEGORIA
		{
			get
			{
				return this.GetTable<CATEGORIA>();
			}
		}
		
		public System.Data.Linq.Table<VEHICULO> VEHICULO
		{
			get
			{
				return this.GetTable<VEHICULO>();
			}
		}
		
		public System.Data.Linq.Table<CLIENTE> CLIENTE
		{
			get
			{
				return this.GetTable<CLIENTE>();
			}
		}
		
		public System.Data.Linq.Table<DETALL_SERVICIO> DETALL_SERVICIO
		{
			get
			{
				return this.GetTable<DETALL_SERVICIO>();
			}
		}
		
		public System.Data.Linq.Table<DETALLE_ORDEN> DETALLE_ORDEN
		{
			get
			{
				return this.GetTable<DETALLE_ORDEN>();
			}
		}
		
		public System.Data.Linq.Table<MARCA> MARCA
		{
			get
			{
				return this.GetTable<MARCA>();
			}
		}
		
		public System.Data.Linq.Table<MODELO> MODELO
		{
			get
			{
				return this.GetTable<MODELO>();
			}
		}
		
		public System.Data.Linq.Table<ORDEN> ORDEN
		{
			get
			{
				return this.GetTable<ORDEN>();
			}
		}
		
		public System.Data.Linq.Table<PRODUCTO> PRODUCTO
		{
			get
			{
				return this.GetTable<PRODUCTO>();
			}
		}
		
		public System.Data.Linq.Table<RESERVA> RESERVA
		{
			get
			{
				return this.GetTable<RESERVA>();
			}
		}
		
		public System.Data.Linq.Table<ROL> ROL
		{
			get
			{
				return this.GetTable<ROL>();
			}
		}
		
		public System.Data.Linq.Table<SERVICIO> SERVICIO
		{
			get
			{
				return this.GetTable<SERVICIO>();
			}
		}
		
		public System.Data.Linq.Table<USUARIO> USUARIO
		{
			get
			{
				return this.GetTable<USUARIO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CATEGORIA")]
	public partial class CATEGORIA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private byte _cat_id;
		
		private string _cat_descripcion;
		
		private char _car_status;
		
		private System.DateTime _car_add;
		
		private EntitySet<PRODUCTO> _PRODUCTO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncat_idChanging(byte value);
    partial void Oncat_idChanged();
    partial void Oncat_descripcionChanging(string value);
    partial void Oncat_descripcionChanged();
    partial void Oncar_statusChanging(char value);
    partial void Oncar_statusChanged();
    partial void Oncar_addChanging(System.DateTime value);
    partial void Oncar_addChanged();
    #endregion
		
		public CATEGORIA()
		{
			this._PRODUCTO = new EntitySet<PRODUCTO>(new Action<PRODUCTO>(this.attach_PRODUCTO), new Action<PRODUCTO>(this.detach_PRODUCTO));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_id", DbType="TinyInt NOT NULL", IsPrimaryKey=true)]
		public byte cat_id
		{
			get
			{
				return this._cat_id;
			}
			set
			{
				if ((this._cat_id != value))
				{
					this.Oncat_idChanging(value);
					this.SendPropertyChanging();
					this._cat_id = value;
					this.SendPropertyChanged("cat_id");
					this.Oncat_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_descripcion", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string cat_descripcion
		{
			get
			{
				return this._cat_descripcion;
			}
			set
			{
				if ((this._cat_descripcion != value))
				{
					this.Oncat_descripcionChanging(value);
					this.SendPropertyChanging();
					this._cat_descripcion = value;
					this.SendPropertyChanged("cat_descripcion");
					this.Oncat_descripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car_status", DbType="Char(1) NOT NULL")]
		public char car_status
		{
			get
			{
				return this._car_status;
			}
			set
			{
				if ((this._car_status != value))
				{
					this.Oncar_statusChanging(value);
					this.SendPropertyChanging();
					this._car_status = value;
					this.SendPropertyChanged("car_status");
					this.Oncar_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car_add", DbType="DateTime NOT NULL")]
		public System.DateTime car_add
		{
			get
			{
				return this._car_add;
			}
			set
			{
				if ((this._car_add != value))
				{
					this.Oncar_addChanging(value);
					this.SendPropertyChanging();
					this._car_add = value;
					this.SendPropertyChanged("car_add");
					this.Oncar_addChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CATEGORIA_PRODUCTO", Storage="_PRODUCTO", ThisKey="cat_id", OtherKey="cat_id")]
		public EntitySet<PRODUCTO> PRODUCTO
		{
			get
			{
				return this._PRODUCTO;
			}
			set
			{
				this._PRODUCTO.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PRODUCTO(PRODUCTO entity)
		{
			this.SendPropertyChanging();
			entity.CATEGORIA = this;
		}
		
		private void detach_PRODUCTO(PRODUCTO entity)
		{
			this.SendPropertyChanging();
			entity.CATEGORIA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VEHICULO")]
	public partial class VEHICULO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _veh_id;
		
		private string _veh_placa;
		
		private string _veh_chasis;
		
		private int _veh_anio;
		
		private string _veh_color;
		
		private short _veh_cilindraje;
		
		private string _veh_motor;
		
		private char _veh_status;
		
		private System.DateTime _aveh_add;
		
		private System.Nullable<int> _mod_id;
		
		private System.Nullable<int> _cli_id;
		
		private EntitySet<ORDEN> _ORDEN;
		
		private EntityRef<CLIENTE> _CLIENTE;
		
		private EntityRef<MODELO> _MODELO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onveh_idChanging(int value);
    partial void Onveh_idChanged();
    partial void Onveh_placaChanging(string value);
    partial void Onveh_placaChanged();
    partial void Onveh_chasisChanging(string value);
    partial void Onveh_chasisChanged();
    partial void Onveh_anioChanging(int value);
    partial void Onveh_anioChanged();
    partial void Onveh_colorChanging(string value);
    partial void Onveh_colorChanged();
    partial void Onveh_cilindrajeChanging(short value);
    partial void Onveh_cilindrajeChanged();
    partial void Onveh_motorChanging(string value);
    partial void Onveh_motorChanged();
    partial void Onveh_statusChanging(char value);
    partial void Onveh_statusChanged();
    partial void Onaveh_addChanging(System.DateTime value);
    partial void Onaveh_addChanged();
    partial void Onmod_idChanging(System.Nullable<int> value);
    partial void Onmod_idChanged();
    partial void Oncli_idChanging(System.Nullable<int> value);
    partial void Oncli_idChanged();
    #endregion
		
		public VEHICULO()
		{
			this._ORDEN = new EntitySet<ORDEN>(new Action<ORDEN>(this.attach_ORDEN), new Action<ORDEN>(this.detach_ORDEN));
			this._CLIENTE = default(EntityRef<CLIENTE>);
			this._MODELO = default(EntityRef<MODELO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_veh_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int veh_id
		{
			get
			{
				return this._veh_id;
			}
			set
			{
				if ((this._veh_id != value))
				{
					this.Onveh_idChanging(value);
					this.SendPropertyChanging();
					this._veh_id = value;
					this.SendPropertyChanged("veh_id");
					this.Onveh_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_veh_placa", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string veh_placa
		{
			get
			{
				return this._veh_placa;
			}
			set
			{
				if ((this._veh_placa != value))
				{
					this.Onveh_placaChanging(value);
					this.SendPropertyChanging();
					this._veh_placa = value;
					this.SendPropertyChanged("veh_placa");
					this.Onveh_placaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_veh_chasis", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string veh_chasis
		{
			get
			{
				return this._veh_chasis;
			}
			set
			{
				if ((this._veh_chasis != value))
				{
					this.Onveh_chasisChanging(value);
					this.SendPropertyChanging();
					this._veh_chasis = value;
					this.SendPropertyChanged("veh_chasis");
					this.Onveh_chasisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_veh_anio", DbType="Int NOT NULL")]
		public int veh_anio
		{
			get
			{
				return this._veh_anio;
			}
			set
			{
				if ((this._veh_anio != value))
				{
					this.Onveh_anioChanging(value);
					this.SendPropertyChanging();
					this._veh_anio = value;
					this.SendPropertyChanged("veh_anio");
					this.Onveh_anioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_veh_color", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string veh_color
		{
			get
			{
				return this._veh_color;
			}
			set
			{
				if ((this._veh_color != value))
				{
					this.Onveh_colorChanging(value);
					this.SendPropertyChanging();
					this._veh_color = value;
					this.SendPropertyChanged("veh_color");
					this.Onveh_colorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_veh_cilindraje", DbType="SmallInt NOT NULL")]
		public short veh_cilindraje
		{
			get
			{
				return this._veh_cilindraje;
			}
			set
			{
				if ((this._veh_cilindraje != value))
				{
					this.Onveh_cilindrajeChanging(value);
					this.SendPropertyChanging();
					this._veh_cilindraje = value;
					this.SendPropertyChanged("veh_cilindraje");
					this.Onveh_cilindrajeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_veh_motor", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string veh_motor
		{
			get
			{
				return this._veh_motor;
			}
			set
			{
				if ((this._veh_motor != value))
				{
					this.Onveh_motorChanging(value);
					this.SendPropertyChanging();
					this._veh_motor = value;
					this.SendPropertyChanged("veh_motor");
					this.Onveh_motorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_veh_status", DbType="Char(1) NOT NULL")]
		public char veh_status
		{
			get
			{
				return this._veh_status;
			}
			set
			{
				if ((this._veh_status != value))
				{
					this.Onveh_statusChanging(value);
					this.SendPropertyChanging();
					this._veh_status = value;
					this.SendPropertyChanged("veh_status");
					this.Onveh_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aveh_add", DbType="DateTime NOT NULL")]
		public System.DateTime aveh_add
		{
			get
			{
				return this._aveh_add;
			}
			set
			{
				if ((this._aveh_add != value))
				{
					this.Onaveh_addChanging(value);
					this.SendPropertyChanging();
					this._aveh_add = value;
					this.SendPropertyChanged("aveh_add");
					this.Onaveh_addChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mod_id", DbType="Int")]
		public System.Nullable<int> mod_id
		{
			get
			{
				return this._mod_id;
			}
			set
			{
				if ((this._mod_id != value))
				{
					if (this._MODELO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onmod_idChanging(value);
					this.SendPropertyChanging();
					this._mod_id = value;
					this.SendPropertyChanged("mod_id");
					this.Onmod_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cli_id", DbType="Int")]
		public System.Nullable<int> cli_id
		{
			get
			{
				return this._cli_id;
			}
			set
			{
				if ((this._cli_id != value))
				{
					if (this._CLIENTE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncli_idChanging(value);
					this.SendPropertyChanging();
					this._cli_id = value;
					this.SendPropertyChanged("cli_id");
					this.Oncli_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VEHICULO_ORDEN", Storage="_ORDEN", ThisKey="veh_id", OtherKey="veh_id")]
		public EntitySet<ORDEN> ORDEN
		{
			get
			{
				return this._ORDEN;
			}
			set
			{
				this._ORDEN.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLIENTE_VEHICULO", Storage="_CLIENTE", ThisKey="cli_id", OtherKey="cli_id", IsForeignKey=true)]
		public CLIENTE CLIENTE
		{
			get
			{
				return this._CLIENTE.Entity;
			}
			set
			{
				CLIENTE previousValue = this._CLIENTE.Entity;
				if (((previousValue != value) 
							|| (this._CLIENTE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CLIENTE.Entity = null;
						previousValue.VEHICULO.Remove(this);
					}
					this._CLIENTE.Entity = value;
					if ((value != null))
					{
						value.VEHICULO.Add(this);
						this._cli_id = value.cli_id;
					}
					else
					{
						this._cli_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("CLIENTE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MODELO_VEHICULO", Storage="_MODELO", ThisKey="mod_id", OtherKey="mod_id", IsForeignKey=true)]
		public MODELO MODELO
		{
			get
			{
				return this._MODELO.Entity;
			}
			set
			{
				MODELO previousValue = this._MODELO.Entity;
				if (((previousValue != value) 
							|| (this._MODELO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MODELO.Entity = null;
						previousValue.VEHICULO.Remove(this);
					}
					this._MODELO.Entity = value;
					if ((value != null))
					{
						value.VEHICULO.Add(this);
						this._mod_id = value.mod_id;
					}
					else
					{
						this._mod_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("MODELO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ORDEN(ORDEN entity)
		{
			this.SendPropertyChanging();
			entity.VEHICULO = this;
		}
		
		private void detach_ORDEN(ORDEN entity)
		{
			this.SendPropertyChanging();
			entity.VEHICULO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CLIENTE")]
	public partial class CLIENTE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cli_id;
		
		private string _cli_identiticacion;
		
		private string _cli_tipoidentificacion;
		
		private string _cli_apellidos;
		
		private string _cli_nombres;
		
		private string _cli_direccion;
		
		private string _cli_telefono;
		
		private string _cli_correo;
		
		private System.Nullable<System.DateTime> _cli_fechanacimiento;
		
		private char _cli_status;
		
		private System.DateTime _cli_add;
		
		private EntitySet<VEHICULO> _VEHICULO;
		
		private EntitySet<RESERVA> _RESERVA;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncli_idChanging(int value);
    partial void Oncli_idChanged();
    partial void Oncli_identiticacionChanging(string value);
    partial void Oncli_identiticacionChanged();
    partial void Oncli_tipoidentificacionChanging(string value);
    partial void Oncli_tipoidentificacionChanged();
    partial void Oncli_apellidosChanging(string value);
    partial void Oncli_apellidosChanged();
    partial void Oncli_nombresChanging(string value);
    partial void Oncli_nombresChanged();
    partial void Oncli_direccionChanging(string value);
    partial void Oncli_direccionChanged();
    partial void Oncli_telefonoChanging(string value);
    partial void Oncli_telefonoChanged();
    partial void Oncli_correoChanging(string value);
    partial void Oncli_correoChanged();
    partial void Oncli_fechanacimientoChanging(System.Nullable<System.DateTime> value);
    partial void Oncli_fechanacimientoChanged();
    partial void Oncli_statusChanging(char value);
    partial void Oncli_statusChanged();
    partial void Oncli_addChanging(System.DateTime value);
    partial void Oncli_addChanged();
    #endregion
		
		public CLIENTE()
		{
			this._VEHICULO = new EntitySet<VEHICULO>(new Action<VEHICULO>(this.attach_VEHICULO), new Action<VEHICULO>(this.detach_VEHICULO));
			this._RESERVA = new EntitySet<RESERVA>(new Action<RESERVA>(this.attach_RESERVA), new Action<RESERVA>(this.detach_RESERVA));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cli_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int cli_id
		{
			get
			{
				return this._cli_id;
			}
			set
			{
				if ((this._cli_id != value))
				{
					this.Oncli_idChanging(value);
					this.SendPropertyChanging();
					this._cli_id = value;
					this.SendPropertyChanged("cli_id");
					this.Oncli_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cli_identiticacion", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string cli_identiticacion
		{
			get
			{
				return this._cli_identiticacion;
			}
			set
			{
				if ((this._cli_identiticacion != value))
				{
					this.Oncli_identiticacionChanging(value);
					this.SendPropertyChanging();
					this._cli_identiticacion = value;
					this.SendPropertyChanged("cli_identiticacion");
					this.Oncli_identiticacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cli_tipoidentificacion", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string cli_tipoidentificacion
		{
			get
			{
				return this._cli_tipoidentificacion;
			}
			set
			{
				if ((this._cli_tipoidentificacion != value))
				{
					this.Oncli_tipoidentificacionChanging(value);
					this.SendPropertyChanging();
					this._cli_tipoidentificacion = value;
					this.SendPropertyChanged("cli_tipoidentificacion");
					this.Oncli_tipoidentificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cli_apellidos", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string cli_apellidos
		{
			get
			{
				return this._cli_apellidos;
			}
			set
			{
				if ((this._cli_apellidos != value))
				{
					this.Oncli_apellidosChanging(value);
					this.SendPropertyChanging();
					this._cli_apellidos = value;
					this.SendPropertyChanged("cli_apellidos");
					this.Oncli_apellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cli_nombres", DbType="NVarChar(60)")]
		public string cli_nombres
		{
			get
			{
				return this._cli_nombres;
			}
			set
			{
				if ((this._cli_nombres != value))
				{
					this.Oncli_nombresChanging(value);
					this.SendPropertyChanging();
					this._cli_nombres = value;
					this.SendPropertyChanged("cli_nombres");
					this.Oncli_nombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cli_direccion", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string cli_direccion
		{
			get
			{
				return this._cli_direccion;
			}
			set
			{
				if ((this._cli_direccion != value))
				{
					this.Oncli_direccionChanging(value);
					this.SendPropertyChanging();
					this._cli_direccion = value;
					this.SendPropertyChanged("cli_direccion");
					this.Oncli_direccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cli_telefono", DbType="VarChar(12)")]
		public string cli_telefono
		{
			get
			{
				return this._cli_telefono;
			}
			set
			{
				if ((this._cli_telefono != value))
				{
					this.Oncli_telefonoChanging(value);
					this.SendPropertyChanging();
					this._cli_telefono = value;
					this.SendPropertyChanged("cli_telefono");
					this.Oncli_telefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cli_correo", DbType="NVarChar(100)")]
		public string cli_correo
		{
			get
			{
				return this._cli_correo;
			}
			set
			{
				if ((this._cli_correo != value))
				{
					this.Oncli_correoChanging(value);
					this.SendPropertyChanging();
					this._cli_correo = value;
					this.SendPropertyChanged("cli_correo");
					this.Oncli_correoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cli_fechanacimiento", DbType="Date")]
		public System.Nullable<System.DateTime> cli_fechanacimiento
		{
			get
			{
				return this._cli_fechanacimiento;
			}
			set
			{
				if ((this._cli_fechanacimiento != value))
				{
					this.Oncli_fechanacimientoChanging(value);
					this.SendPropertyChanging();
					this._cli_fechanacimiento = value;
					this.SendPropertyChanged("cli_fechanacimiento");
					this.Oncli_fechanacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cli_status", DbType="Char(1) NOT NULL")]
		public char cli_status
		{
			get
			{
				return this._cli_status;
			}
			set
			{
				if ((this._cli_status != value))
				{
					this.Oncli_statusChanging(value);
					this.SendPropertyChanging();
					this._cli_status = value;
					this.SendPropertyChanged("cli_status");
					this.Oncli_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cli_add", DbType="DateTime NOT NULL")]
		public System.DateTime cli_add
		{
			get
			{
				return this._cli_add;
			}
			set
			{
				if ((this._cli_add != value))
				{
					this.Oncli_addChanging(value);
					this.SendPropertyChanging();
					this._cli_add = value;
					this.SendPropertyChanged("cli_add");
					this.Oncli_addChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLIENTE_VEHICULO", Storage="_VEHICULO", ThisKey="cli_id", OtherKey="cli_id")]
		public EntitySet<VEHICULO> VEHICULO
		{
			get
			{
				return this._VEHICULO;
			}
			set
			{
				this._VEHICULO.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLIENTE_RESERVA", Storage="_RESERVA", ThisKey="cli_id", OtherKey="cli_id")]
		public EntitySet<RESERVA> RESERVA
		{
			get
			{
				return this._RESERVA;
			}
			set
			{
				this._RESERVA.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_VEHICULO(VEHICULO entity)
		{
			this.SendPropertyChanging();
			entity.CLIENTE = this;
		}
		
		private void detach_VEHICULO(VEHICULO entity)
		{
			this.SendPropertyChanging();
			entity.CLIENTE = null;
		}
		
		private void attach_RESERVA(RESERVA entity)
		{
			this.SendPropertyChanging();
			entity.CLIENTE = this;
		}
		
		private void detach_RESERVA(RESERVA entity)
		{
			this.SendPropertyChanging();
			entity.CLIENTE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DETALL_SERVICIO")]
	public partial class DETALL_SERVICIO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _dse_descripcion;
		
		private System.Nullable<int> _ord_id;
		
		private System.Nullable<int> _ser_id;
		
		private EntityRef<ORDEN> _ORDEN;
		
		private EntityRef<SERVICIO> _SERVICIO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondse_descripcionChanging(short value);
    partial void Ondse_descripcionChanged();
    partial void Onord_idChanging(System.Nullable<int> value);
    partial void Onord_idChanged();
    partial void Onser_idChanging(System.Nullable<int> value);
    partial void Onser_idChanged();
    #endregion
		
		public DETALL_SERVICIO()
		{
			this._ORDEN = default(EntityRef<ORDEN>);
			this._SERVICIO = default(EntityRef<SERVICIO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dse_descripcion", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short dse_descripcion
		{
			get
			{
				return this._dse_descripcion;
			}
			set
			{
				if ((this._dse_descripcion != value))
				{
					this.Ondse_descripcionChanging(value);
					this.SendPropertyChanging();
					this._dse_descripcion = value;
					this.SendPropertyChanged("dse_descripcion");
					this.Ondse_descripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ord_id", DbType="Int")]
		public System.Nullable<int> ord_id
		{
			get
			{
				return this._ord_id;
			}
			set
			{
				if ((this._ord_id != value))
				{
					if (this._ORDEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onord_idChanging(value);
					this.SendPropertyChanging();
					this._ord_id = value;
					this.SendPropertyChanged("ord_id");
					this.Onord_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ser_id", DbType="Int")]
		public System.Nullable<int> ser_id
		{
			get
			{
				return this._ser_id;
			}
			set
			{
				if ((this._ser_id != value))
				{
					if (this._SERVICIO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onser_idChanging(value);
					this.SendPropertyChanging();
					this._ser_id = value;
					this.SendPropertyChanged("ser_id");
					this.Onser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ORDEN_DETALL_SERVICIO", Storage="_ORDEN", ThisKey="ord_id", OtherKey="ord_id", IsForeignKey=true)]
		public ORDEN ORDEN
		{
			get
			{
				return this._ORDEN.Entity;
			}
			set
			{
				ORDEN previousValue = this._ORDEN.Entity;
				if (((previousValue != value) 
							|| (this._ORDEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ORDEN.Entity = null;
						previousValue.DETALL_SERVICIO.Remove(this);
					}
					this._ORDEN.Entity = value;
					if ((value != null))
					{
						value.DETALL_SERVICIO.Add(this);
						this._ord_id = value.ord_id;
					}
					else
					{
						this._ord_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("ORDEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SERVICIO_DETALL_SERVICIO", Storage="_SERVICIO", ThisKey="ser_id", OtherKey="ser_id", IsForeignKey=true)]
		public SERVICIO SERVICIO
		{
			get
			{
				return this._SERVICIO.Entity;
			}
			set
			{
				SERVICIO previousValue = this._SERVICIO.Entity;
				if (((previousValue != value) 
							|| (this._SERVICIO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SERVICIO.Entity = null;
						previousValue.DETALL_SERVICIO.Remove(this);
					}
					this._SERVICIO.Entity = value;
					if ((value != null))
					{
						value.DETALL_SERVICIO.Add(this);
						this._ser_id = value.ser_id;
					}
					else
					{
						this._ser_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("SERVICIO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DETALLE_ORDEN")]
	public partial class DETALLE_ORDEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _deo_id;
		
		private System.Nullable<int> _ord_id;
		
		private System.Nullable<int> _pro_id;
		
		private EntityRef<ORDEN> _ORDEN;
		
		private EntityRef<PRODUCTO> _PRODUCTO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondeo_idChanging(short value);
    partial void Ondeo_idChanged();
    partial void Onord_idChanging(System.Nullable<int> value);
    partial void Onord_idChanged();
    partial void Onpro_idChanging(System.Nullable<int> value);
    partial void Onpro_idChanged();
    #endregion
		
		public DETALLE_ORDEN()
		{
			this._ORDEN = default(EntityRef<ORDEN>);
			this._PRODUCTO = default(EntityRef<PRODUCTO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deo_id", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short deo_id
		{
			get
			{
				return this._deo_id;
			}
			set
			{
				if ((this._deo_id != value))
				{
					this.Ondeo_idChanging(value);
					this.SendPropertyChanging();
					this._deo_id = value;
					this.SendPropertyChanged("deo_id");
					this.Ondeo_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ord_id", DbType="Int")]
		public System.Nullable<int> ord_id
		{
			get
			{
				return this._ord_id;
			}
			set
			{
				if ((this._ord_id != value))
				{
					if (this._ORDEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onord_idChanging(value);
					this.SendPropertyChanging();
					this._ord_id = value;
					this.SendPropertyChanged("ord_id");
					this.Onord_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_id", DbType="Int")]
		public System.Nullable<int> pro_id
		{
			get
			{
				return this._pro_id;
			}
			set
			{
				if ((this._pro_id != value))
				{
					if (this._PRODUCTO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onpro_idChanging(value);
					this.SendPropertyChanging();
					this._pro_id = value;
					this.SendPropertyChanged("pro_id");
					this.Onpro_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ORDEN_DETALLE_ORDEN", Storage="_ORDEN", ThisKey="ord_id", OtherKey="ord_id", IsForeignKey=true)]
		public ORDEN ORDEN
		{
			get
			{
				return this._ORDEN.Entity;
			}
			set
			{
				ORDEN previousValue = this._ORDEN.Entity;
				if (((previousValue != value) 
							|| (this._ORDEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ORDEN.Entity = null;
						previousValue.DETALLE_ORDEN.Remove(this);
					}
					this._ORDEN.Entity = value;
					if ((value != null))
					{
						value.DETALLE_ORDEN.Add(this);
						this._ord_id = value.ord_id;
					}
					else
					{
						this._ord_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("ORDEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PRODUCTO_DETALLE_ORDEN", Storage="_PRODUCTO", ThisKey="pro_id", OtherKey="pro_id", IsForeignKey=true)]
		public PRODUCTO PRODUCTO
		{
			get
			{
				return this._PRODUCTO.Entity;
			}
			set
			{
				PRODUCTO previousValue = this._PRODUCTO.Entity;
				if (((previousValue != value) 
							|| (this._PRODUCTO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PRODUCTO.Entity = null;
						previousValue.DETALLE_ORDEN.Remove(this);
					}
					this._PRODUCTO.Entity = value;
					if ((value != null))
					{
						value.DETALLE_ORDEN.Add(this);
						this._pro_id = value.pro_id;
					}
					else
					{
						this._pro_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("PRODUCTO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MARCA")]
	public partial class MARCA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _mar_id;
		
		private string _mar_descripcion;
		
		private char _mar_status;
		
		private System.DateTime _mar_add;
		
		private EntitySet<MODELO> _MODELO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmar_idChanging(short value);
    partial void Onmar_idChanged();
    partial void Onmar_descripcionChanging(string value);
    partial void Onmar_descripcionChanged();
    partial void Onmar_statusChanging(char value);
    partial void Onmar_statusChanged();
    partial void Onmar_addChanging(System.DateTime value);
    partial void Onmar_addChanged();
    #endregion
		
		public MARCA()
		{
			this._MODELO = new EntitySet<MODELO>(new Action<MODELO>(this.attach_MODELO), new Action<MODELO>(this.detach_MODELO));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mar_id", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short mar_id
		{
			get
			{
				return this._mar_id;
			}
			set
			{
				if ((this._mar_id != value))
				{
					this.Onmar_idChanging(value);
					this.SendPropertyChanging();
					this._mar_id = value;
					this.SendPropertyChanged("mar_id");
					this.Onmar_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mar_descripcion", DbType="NVarChar(80) NOT NULL", CanBeNull=false)]
		public string mar_descripcion
		{
			get
			{
				return this._mar_descripcion;
			}
			set
			{
				if ((this._mar_descripcion != value))
				{
					this.Onmar_descripcionChanging(value);
					this.SendPropertyChanging();
					this._mar_descripcion = value;
					this.SendPropertyChanged("mar_descripcion");
					this.Onmar_descripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mar_status", DbType="Char(1) NOT NULL")]
		public char mar_status
		{
			get
			{
				return this._mar_status;
			}
			set
			{
				if ((this._mar_status != value))
				{
					this.Onmar_statusChanging(value);
					this.SendPropertyChanging();
					this._mar_status = value;
					this.SendPropertyChanged("mar_status");
					this.Onmar_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mar_add", DbType="DateTime NOT NULL")]
		public System.DateTime mar_add
		{
			get
			{
				return this._mar_add;
			}
			set
			{
				if ((this._mar_add != value))
				{
					this.Onmar_addChanging(value);
					this.SendPropertyChanging();
					this._mar_add = value;
					this.SendPropertyChanged("mar_add");
					this.Onmar_addChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MARCA_MODELO", Storage="_MODELO", ThisKey="mar_id", OtherKey="mar_id")]
		public EntitySet<MODELO> MODELO
		{
			get
			{
				return this._MODELO;
			}
			set
			{
				this._MODELO.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MODELO(MODELO entity)
		{
			this.SendPropertyChanging();
			entity.MARCA = this;
		}
		
		private void detach_MODELO(MODELO entity)
		{
			this.SendPropertyChanging();
			entity.MARCA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MODELO")]
	public partial class MODELO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _mod_id;
		
		private string _mod_descripcion;
		
		private char _mod_status;
		
		private System.DateTime _mod_add;
		
		private System.Nullable<short> _mar_id;
		
		private EntitySet<VEHICULO> _VEHICULO;
		
		private EntityRef<MARCA> _MARCA;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmod_idChanging(int value);
    partial void Onmod_idChanged();
    partial void Onmod_descripcionChanging(string value);
    partial void Onmod_descripcionChanged();
    partial void Onmod_statusChanging(char value);
    partial void Onmod_statusChanged();
    partial void Onmod_addChanging(System.DateTime value);
    partial void Onmod_addChanged();
    partial void Onmar_idChanging(System.Nullable<short> value);
    partial void Onmar_idChanged();
    #endregion
		
		public MODELO()
		{
			this._VEHICULO = new EntitySet<VEHICULO>(new Action<VEHICULO>(this.attach_VEHICULO), new Action<VEHICULO>(this.detach_VEHICULO));
			this._MARCA = default(EntityRef<MARCA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mod_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int mod_id
		{
			get
			{
				return this._mod_id;
			}
			set
			{
				if ((this._mod_id != value))
				{
					this.Onmod_idChanging(value);
					this.SendPropertyChanging();
					this._mod_id = value;
					this.SendPropertyChanged("mod_id");
					this.Onmod_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mod_descripcion", DbType="NVarChar(80) NOT NULL", CanBeNull=false)]
		public string mod_descripcion
		{
			get
			{
				return this._mod_descripcion;
			}
			set
			{
				if ((this._mod_descripcion != value))
				{
					this.Onmod_descripcionChanging(value);
					this.SendPropertyChanging();
					this._mod_descripcion = value;
					this.SendPropertyChanged("mod_descripcion");
					this.Onmod_descripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mod_status", DbType="Char(1) NOT NULL")]
		public char mod_status
		{
			get
			{
				return this._mod_status;
			}
			set
			{
				if ((this._mod_status != value))
				{
					this.Onmod_statusChanging(value);
					this.SendPropertyChanging();
					this._mod_status = value;
					this.SendPropertyChanged("mod_status");
					this.Onmod_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mod_add", DbType="DateTime NOT NULL")]
		public System.DateTime mod_add
		{
			get
			{
				return this._mod_add;
			}
			set
			{
				if ((this._mod_add != value))
				{
					this.Onmod_addChanging(value);
					this.SendPropertyChanging();
					this._mod_add = value;
					this.SendPropertyChanged("mod_add");
					this.Onmod_addChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mar_id", DbType="SmallInt")]
		public System.Nullable<short> mar_id
		{
			get
			{
				return this._mar_id;
			}
			set
			{
				if ((this._mar_id != value))
				{
					if (this._MARCA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onmar_idChanging(value);
					this.SendPropertyChanging();
					this._mar_id = value;
					this.SendPropertyChanged("mar_id");
					this.Onmar_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MODELO_VEHICULO", Storage="_VEHICULO", ThisKey="mod_id", OtherKey="mod_id")]
		public EntitySet<VEHICULO> VEHICULO
		{
			get
			{
				return this._VEHICULO;
			}
			set
			{
				this._VEHICULO.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MARCA_MODELO", Storage="_MARCA", ThisKey="mar_id", OtherKey="mar_id", IsForeignKey=true)]
		public MARCA MARCA
		{
			get
			{
				return this._MARCA.Entity;
			}
			set
			{
				MARCA previousValue = this._MARCA.Entity;
				if (((previousValue != value) 
							|| (this._MARCA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MARCA.Entity = null;
						previousValue.MODELO.Remove(this);
					}
					this._MARCA.Entity = value;
					if ((value != null))
					{
						value.MODELO.Add(this);
						this._mar_id = value.mar_id;
					}
					else
					{
						this._mar_id = default(Nullable<short>);
					}
					this.SendPropertyChanged("MARCA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_VEHICULO(VEHICULO entity)
		{
			this.SendPropertyChanging();
			entity.MODELO = this;
		}
		
		private void detach_VEHICULO(VEHICULO entity)
		{
			this.SendPropertyChanging();
			entity.MODELO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ORDEN")]
	public partial class ORDEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ord_id;
		
		private System.Nullable<System.DateTime> _ord_fecha;
		
		private int _ord_kilometraje;
		
		private string _ord_observacion;
		
		private char _ord_status;
		
		private System.DateTime _ord_add;
		
		private System.Nullable<int> _veh_id;
		
		private EntitySet<DETALL_SERVICIO> _DETALL_SERVICIO;
		
		private EntitySet<DETALLE_ORDEN> _DETALLE_ORDEN;
		
		private EntityRef<VEHICULO> _VEHICULO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onord_idChanging(int value);
    partial void Onord_idChanged();
    partial void Onord_fechaChanging(System.Nullable<System.DateTime> value);
    partial void Onord_fechaChanged();
    partial void Onord_kilometrajeChanging(int value);
    partial void Onord_kilometrajeChanged();
    partial void Onord_observacionChanging(string value);
    partial void Onord_observacionChanged();
    partial void Onord_statusChanging(char value);
    partial void Onord_statusChanged();
    partial void Onord_addChanging(System.DateTime value);
    partial void Onord_addChanged();
    partial void Onveh_idChanging(System.Nullable<int> value);
    partial void Onveh_idChanged();
    #endregion
		
		public ORDEN()
		{
			this._DETALL_SERVICIO = new EntitySet<DETALL_SERVICIO>(new Action<DETALL_SERVICIO>(this.attach_DETALL_SERVICIO), new Action<DETALL_SERVICIO>(this.detach_DETALL_SERVICIO));
			this._DETALLE_ORDEN = new EntitySet<DETALLE_ORDEN>(new Action<DETALLE_ORDEN>(this.attach_DETALLE_ORDEN), new Action<DETALLE_ORDEN>(this.detach_DETALLE_ORDEN));
			this._VEHICULO = default(EntityRef<VEHICULO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ord_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ord_id
		{
			get
			{
				return this._ord_id;
			}
			set
			{
				if ((this._ord_id != value))
				{
					this.Onord_idChanging(value);
					this.SendPropertyChanging();
					this._ord_id = value;
					this.SendPropertyChanged("ord_id");
					this.Onord_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ord_fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> ord_fecha
		{
			get
			{
				return this._ord_fecha;
			}
			set
			{
				if ((this._ord_fecha != value))
				{
					this.Onord_fechaChanging(value);
					this.SendPropertyChanging();
					this._ord_fecha = value;
					this.SendPropertyChanged("ord_fecha");
					this.Onord_fechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ord_kilometraje", DbType="Int NOT NULL")]
		public int ord_kilometraje
		{
			get
			{
				return this._ord_kilometraje;
			}
			set
			{
				if ((this._ord_kilometraje != value))
				{
					this.Onord_kilometrajeChanging(value);
					this.SendPropertyChanging();
					this._ord_kilometraje = value;
					this.SendPropertyChanged("ord_kilometraje");
					this.Onord_kilometrajeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ord_observacion", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string ord_observacion
		{
			get
			{
				return this._ord_observacion;
			}
			set
			{
				if ((this._ord_observacion != value))
				{
					this.Onord_observacionChanging(value);
					this.SendPropertyChanging();
					this._ord_observacion = value;
					this.SendPropertyChanged("ord_observacion");
					this.Onord_observacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ord_status", DbType="Char(1) NOT NULL")]
		public char ord_status
		{
			get
			{
				return this._ord_status;
			}
			set
			{
				if ((this._ord_status != value))
				{
					this.Onord_statusChanging(value);
					this.SendPropertyChanging();
					this._ord_status = value;
					this.SendPropertyChanged("ord_status");
					this.Onord_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ord_add", DbType="DateTime NOT NULL")]
		public System.DateTime ord_add
		{
			get
			{
				return this._ord_add;
			}
			set
			{
				if ((this._ord_add != value))
				{
					this.Onord_addChanging(value);
					this.SendPropertyChanging();
					this._ord_add = value;
					this.SendPropertyChanged("ord_add");
					this.Onord_addChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_veh_id", DbType="Int")]
		public System.Nullable<int> veh_id
		{
			get
			{
				return this._veh_id;
			}
			set
			{
				if ((this._veh_id != value))
				{
					if (this._VEHICULO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onveh_idChanging(value);
					this.SendPropertyChanging();
					this._veh_id = value;
					this.SendPropertyChanged("veh_id");
					this.Onveh_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ORDEN_DETALL_SERVICIO", Storage="_DETALL_SERVICIO", ThisKey="ord_id", OtherKey="ord_id")]
		public EntitySet<DETALL_SERVICIO> DETALL_SERVICIO
		{
			get
			{
				return this._DETALL_SERVICIO;
			}
			set
			{
				this._DETALL_SERVICIO.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ORDEN_DETALLE_ORDEN", Storage="_DETALLE_ORDEN", ThisKey="ord_id", OtherKey="ord_id")]
		public EntitySet<DETALLE_ORDEN> DETALLE_ORDEN
		{
			get
			{
				return this._DETALLE_ORDEN;
			}
			set
			{
				this._DETALLE_ORDEN.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VEHICULO_ORDEN", Storage="_VEHICULO", ThisKey="veh_id", OtherKey="veh_id", IsForeignKey=true)]
		public VEHICULO VEHICULO
		{
			get
			{
				return this._VEHICULO.Entity;
			}
			set
			{
				VEHICULO previousValue = this._VEHICULO.Entity;
				if (((previousValue != value) 
							|| (this._VEHICULO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._VEHICULO.Entity = null;
						previousValue.ORDEN.Remove(this);
					}
					this._VEHICULO.Entity = value;
					if ((value != null))
					{
						value.ORDEN.Add(this);
						this._veh_id = value.veh_id;
					}
					else
					{
						this._veh_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("VEHICULO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DETALL_SERVICIO(DETALL_SERVICIO entity)
		{
			this.SendPropertyChanging();
			entity.ORDEN = this;
		}
		
		private void detach_DETALL_SERVICIO(DETALL_SERVICIO entity)
		{
			this.SendPropertyChanging();
			entity.ORDEN = null;
		}
		
		private void attach_DETALLE_ORDEN(DETALLE_ORDEN entity)
		{
			this.SendPropertyChanging();
			entity.ORDEN = this;
		}
		
		private void detach_DETALLE_ORDEN(DETALLE_ORDEN entity)
		{
			this.SendPropertyChanging();
			entity.ORDEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PRODUCTO")]
	public partial class PRODUCTO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pro_id;
		
		private string _pro_codigo;
		
		private string _pro_nombre;
		
		private decimal _pro_precio;
		
		private int _pro_stockminimo;
		
		private int _pro_stokcmaximo;
		
		private bool _pro_original;
		
		private string _pro_observacion;
		
		private char _pro_status;
		
		private System.DateTime _pro_add;
		
		private System.Nullable<byte> _cat_id;
		
		private EntitySet<DETALLE_ORDEN> _DETALLE_ORDEN;
		
		private EntityRef<CATEGORIA> _CATEGORIA;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpro_idChanging(int value);
    partial void Onpro_idChanged();
    partial void Onpro_codigoChanging(string value);
    partial void Onpro_codigoChanged();
    partial void Onpro_nombreChanging(string value);
    partial void Onpro_nombreChanged();
    partial void Onpro_precioChanging(decimal value);
    partial void Onpro_precioChanged();
    partial void Onpro_stockminimoChanging(int value);
    partial void Onpro_stockminimoChanged();
    partial void Onpro_stokcmaximoChanging(int value);
    partial void Onpro_stokcmaximoChanged();
    partial void Onpro_originalChanging(bool value);
    partial void Onpro_originalChanged();
    partial void Onpro_observacionChanging(string value);
    partial void Onpro_observacionChanged();
    partial void Onpro_statusChanging(char value);
    partial void Onpro_statusChanged();
    partial void Onpro_addChanging(System.DateTime value);
    partial void Onpro_addChanged();
    partial void Oncat_idChanging(System.Nullable<byte> value);
    partial void Oncat_idChanged();
    #endregion
		
		public PRODUCTO()
		{
			this._DETALLE_ORDEN = new EntitySet<DETALLE_ORDEN>(new Action<DETALLE_ORDEN>(this.attach_DETALLE_ORDEN), new Action<DETALLE_ORDEN>(this.detach_DETALLE_ORDEN));
			this._CATEGORIA = default(EntityRef<CATEGORIA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int pro_id
		{
			get
			{
				return this._pro_id;
			}
			set
			{
				if ((this._pro_id != value))
				{
					this.Onpro_idChanging(value);
					this.SendPropertyChanging();
					this._pro_id = value;
					this.SendPropertyChanged("pro_id");
					this.Onpro_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_codigo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string pro_codigo
		{
			get
			{
				return this._pro_codigo;
			}
			set
			{
				if ((this._pro_codigo != value))
				{
					this.Onpro_codigoChanging(value);
					this.SendPropertyChanging();
					this._pro_codigo = value;
					this.SendPropertyChanged("pro_codigo");
					this.Onpro_codigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_nombre", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string pro_nombre
		{
			get
			{
				return this._pro_nombre;
			}
			set
			{
				if ((this._pro_nombre != value))
				{
					this.Onpro_nombreChanging(value);
					this.SendPropertyChanging();
					this._pro_nombre = value;
					this.SendPropertyChanged("pro_nombre");
					this.Onpro_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_precio", DbType="Decimal(8,2) NOT NULL")]
		public decimal pro_precio
		{
			get
			{
				return this._pro_precio;
			}
			set
			{
				if ((this._pro_precio != value))
				{
					this.Onpro_precioChanging(value);
					this.SendPropertyChanging();
					this._pro_precio = value;
					this.SendPropertyChanged("pro_precio");
					this.Onpro_precioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_stockminimo", DbType="Int NOT NULL")]
		public int pro_stockminimo
		{
			get
			{
				return this._pro_stockminimo;
			}
			set
			{
				if ((this._pro_stockminimo != value))
				{
					this.Onpro_stockminimoChanging(value);
					this.SendPropertyChanging();
					this._pro_stockminimo = value;
					this.SendPropertyChanged("pro_stockminimo");
					this.Onpro_stockminimoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_stokcmaximo", DbType="Int NOT NULL")]
		public int pro_stokcmaximo
		{
			get
			{
				return this._pro_stokcmaximo;
			}
			set
			{
				if ((this._pro_stokcmaximo != value))
				{
					this.Onpro_stokcmaximoChanging(value);
					this.SendPropertyChanging();
					this._pro_stokcmaximo = value;
					this.SendPropertyChanged("pro_stokcmaximo");
					this.Onpro_stokcmaximoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_original", DbType="Bit NOT NULL")]
		public bool pro_original
		{
			get
			{
				return this._pro_original;
			}
			set
			{
				if ((this._pro_original != value))
				{
					this.Onpro_originalChanging(value);
					this.SendPropertyChanging();
					this._pro_original = value;
					this.SendPropertyChanged("pro_original");
					this.Onpro_originalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_observacion", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string pro_observacion
		{
			get
			{
				return this._pro_observacion;
			}
			set
			{
				if ((this._pro_observacion != value))
				{
					this.Onpro_observacionChanging(value);
					this.SendPropertyChanging();
					this._pro_observacion = value;
					this.SendPropertyChanged("pro_observacion");
					this.Onpro_observacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_status", DbType="Char(1) NOT NULL")]
		public char pro_status
		{
			get
			{
				return this._pro_status;
			}
			set
			{
				if ((this._pro_status != value))
				{
					this.Onpro_statusChanging(value);
					this.SendPropertyChanging();
					this._pro_status = value;
					this.SendPropertyChanged("pro_status");
					this.Onpro_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_add", DbType="DateTime NOT NULL")]
		public System.DateTime pro_add
		{
			get
			{
				return this._pro_add;
			}
			set
			{
				if ((this._pro_add != value))
				{
					this.Onpro_addChanging(value);
					this.SendPropertyChanging();
					this._pro_add = value;
					this.SendPropertyChanged("pro_add");
					this.Onpro_addChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_id", DbType="TinyInt")]
		public System.Nullable<byte> cat_id
		{
			get
			{
				return this._cat_id;
			}
			set
			{
				if ((this._cat_id != value))
				{
					if (this._CATEGORIA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncat_idChanging(value);
					this.SendPropertyChanging();
					this._cat_id = value;
					this.SendPropertyChanged("cat_id");
					this.Oncat_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PRODUCTO_DETALLE_ORDEN", Storage="_DETALLE_ORDEN", ThisKey="pro_id", OtherKey="pro_id")]
		public EntitySet<DETALLE_ORDEN> DETALLE_ORDEN
		{
			get
			{
				return this._DETALLE_ORDEN;
			}
			set
			{
				this._DETALLE_ORDEN.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CATEGORIA_PRODUCTO", Storage="_CATEGORIA", ThisKey="cat_id", OtherKey="cat_id", IsForeignKey=true)]
		public CATEGORIA CATEGORIA
		{
			get
			{
				return this._CATEGORIA.Entity;
			}
			set
			{
				CATEGORIA previousValue = this._CATEGORIA.Entity;
				if (((previousValue != value) 
							|| (this._CATEGORIA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CATEGORIA.Entity = null;
						previousValue.PRODUCTO.Remove(this);
					}
					this._CATEGORIA.Entity = value;
					if ((value != null))
					{
						value.PRODUCTO.Add(this);
						this._cat_id = value.cat_id;
					}
					else
					{
						this._cat_id = default(Nullable<byte>);
					}
					this.SendPropertyChanged("CATEGORIA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DETALLE_ORDEN(DETALLE_ORDEN entity)
		{
			this.SendPropertyChanging();
			entity.PRODUCTO = this;
		}
		
		private void detach_DETALLE_ORDEN(DETALLE_ORDEN entity)
		{
			this.SendPropertyChanging();
			entity.PRODUCTO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RESERVA")]
	public partial class RESERVA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _res_id;
		
		private System.DateTime _res_fecha;
		
		private int _res_numero;
		
		private string _res_observacion;
		
		private char _res_status;
		
		private System.DateTime _res_add;
		
		private System.Nullable<int> _cli_id;
		
		private EntityRef<CLIENTE> _CLIENTE;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onres_idChanging(int value);
    partial void Onres_idChanged();
    partial void Onres_fechaChanging(System.DateTime value);
    partial void Onres_fechaChanged();
    partial void Onres_numeroChanging(int value);
    partial void Onres_numeroChanged();
    partial void Onres_observacionChanging(string value);
    partial void Onres_observacionChanged();
    partial void Onres_statusChanging(char value);
    partial void Onres_statusChanged();
    partial void Onres_addChanging(System.DateTime value);
    partial void Onres_addChanged();
    partial void Oncli_idChanging(System.Nullable<int> value);
    partial void Oncli_idChanged();
    #endregion
		
		public RESERVA()
		{
			this._CLIENTE = default(EntityRef<CLIENTE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_res_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int res_id
		{
			get
			{
				return this._res_id;
			}
			set
			{
				if ((this._res_id != value))
				{
					this.Onres_idChanging(value);
					this.SendPropertyChanging();
					this._res_id = value;
					this.SendPropertyChanged("res_id");
					this.Onres_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_res_fecha", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime res_fecha
		{
			get
			{
				return this._res_fecha;
			}
			set
			{
				if ((this._res_fecha != value))
				{
					this.Onres_fechaChanging(value);
					this.SendPropertyChanging();
					this._res_fecha = value;
					this.SendPropertyChanged("res_fecha");
					this.Onres_fechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_res_numero", DbType="Int NOT NULL")]
		public int res_numero
		{
			get
			{
				return this._res_numero;
			}
			set
			{
				if ((this._res_numero != value))
				{
					this.Onres_numeroChanging(value);
					this.SendPropertyChanging();
					this._res_numero = value;
					this.SendPropertyChanged("res_numero");
					this.Onres_numeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_res_observacion", DbType="NVarChar(200)")]
		public string res_observacion
		{
			get
			{
				return this._res_observacion;
			}
			set
			{
				if ((this._res_observacion != value))
				{
					this.Onres_observacionChanging(value);
					this.SendPropertyChanging();
					this._res_observacion = value;
					this.SendPropertyChanged("res_observacion");
					this.Onres_observacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_res_status", DbType="Char(1) NOT NULL")]
		public char res_status
		{
			get
			{
				return this._res_status;
			}
			set
			{
				if ((this._res_status != value))
				{
					this.Onres_statusChanging(value);
					this.SendPropertyChanging();
					this._res_status = value;
					this.SendPropertyChanged("res_status");
					this.Onres_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_res_add", DbType="DateTime NOT NULL")]
		public System.DateTime res_add
		{
			get
			{
				return this._res_add;
			}
			set
			{
				if ((this._res_add != value))
				{
					this.Onres_addChanging(value);
					this.SendPropertyChanging();
					this._res_add = value;
					this.SendPropertyChanged("res_add");
					this.Onres_addChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cli_id", DbType="Int")]
		public System.Nullable<int> cli_id
		{
			get
			{
				return this._cli_id;
			}
			set
			{
				if ((this._cli_id != value))
				{
					if (this._CLIENTE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncli_idChanging(value);
					this.SendPropertyChanging();
					this._cli_id = value;
					this.SendPropertyChanged("cli_id");
					this.Oncli_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLIENTE_RESERVA", Storage="_CLIENTE", ThisKey="cli_id", OtherKey="cli_id", IsForeignKey=true)]
		public CLIENTE CLIENTE
		{
			get
			{
				return this._CLIENTE.Entity;
			}
			set
			{
				CLIENTE previousValue = this._CLIENTE.Entity;
				if (((previousValue != value) 
							|| (this._CLIENTE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CLIENTE.Entity = null;
						previousValue.RESERVA.Remove(this);
					}
					this._CLIENTE.Entity = value;
					if ((value != null))
					{
						value.RESERVA.Add(this);
						this._cli_id = value.cli_id;
					}
					else
					{
						this._cli_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("CLIENTE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ROL")]
	public partial class ROL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _rol_id;
		
		private string _rol_descripcion;
		
		private char _rol_status;
		
		private System.DateTime _rol_add;
		
		private EntitySet<USUARIO> _USUARIO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onrol_idChanging(int value);
    partial void Onrol_idChanged();
    partial void Onrol_descripcionChanging(string value);
    partial void Onrol_descripcionChanged();
    partial void Onrol_statusChanging(char value);
    partial void Onrol_statusChanged();
    partial void Onrol_addChanging(System.DateTime value);
    partial void Onrol_addChanged();
    #endregion
		
		public ROL()
		{
			this._USUARIO = new EntitySet<USUARIO>(new Action<USUARIO>(this.attach_USUARIO), new Action<USUARIO>(this.detach_USUARIO));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int rol_id
		{
			get
			{
				return this._rol_id;
			}
			set
			{
				if ((this._rol_id != value))
				{
					this.Onrol_idChanging(value);
					this.SendPropertyChanging();
					this._rol_id = value;
					this.SendPropertyChanged("rol_id");
					this.Onrol_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol_descripcion", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string rol_descripcion
		{
			get
			{
				return this._rol_descripcion;
			}
			set
			{
				if ((this._rol_descripcion != value))
				{
					this.Onrol_descripcionChanging(value);
					this.SendPropertyChanging();
					this._rol_descripcion = value;
					this.SendPropertyChanged("rol_descripcion");
					this.Onrol_descripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol_status", DbType="Char(1) NOT NULL")]
		public char rol_status
		{
			get
			{
				return this._rol_status;
			}
			set
			{
				if ((this._rol_status != value))
				{
					this.Onrol_statusChanging(value);
					this.SendPropertyChanging();
					this._rol_status = value;
					this.SendPropertyChanged("rol_status");
					this.Onrol_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol_add", DbType="DateTime NOT NULL")]
		public System.DateTime rol_add
		{
			get
			{
				return this._rol_add;
			}
			set
			{
				if ((this._rol_add != value))
				{
					this.Onrol_addChanging(value);
					this.SendPropertyChanging();
					this._rol_add = value;
					this.SendPropertyChanged("rol_add");
					this.Onrol_addChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ROL_USUARIO", Storage="_USUARIO", ThisKey="rol_id", OtherKey="rol_id")]
		public EntitySet<USUARIO> USUARIO
		{
			get
			{
				return this._USUARIO;
			}
			set
			{
				this._USUARIO.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_USUARIO(USUARIO entity)
		{
			this.SendPropertyChanging();
			entity.ROL = this;
		}
		
		private void detach_USUARIO(USUARIO entity)
		{
			this.SendPropertyChanging();
			entity.ROL = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SERVICIO")]
	public partial class SERVICIO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ser_id;
		
		private string _ser_nombre;
		
		private decimal _ser_precio;
		
		private string _ser_observacion;
		
		private char _ser_status;
		
		private System.DateTime _ser_add;
		
		private EntitySet<DETALL_SERVICIO> _DETALL_SERVICIO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onser_idChanging(int value);
    partial void Onser_idChanged();
    partial void Onser_nombreChanging(string value);
    partial void Onser_nombreChanged();
    partial void Onser_precioChanging(decimal value);
    partial void Onser_precioChanged();
    partial void Onser_observacionChanging(string value);
    partial void Onser_observacionChanged();
    partial void Onser_statusChanging(char value);
    partial void Onser_statusChanged();
    partial void Onser_addChanging(System.DateTime value);
    partial void Onser_addChanged();
    #endregion
		
		public SERVICIO()
		{
			this._DETALL_SERVICIO = new EntitySet<DETALL_SERVICIO>(new Action<DETALL_SERVICIO>(this.attach_DETALL_SERVICIO), new Action<DETALL_SERVICIO>(this.detach_DETALL_SERVICIO));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ser_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ser_id
		{
			get
			{
				return this._ser_id;
			}
			set
			{
				if ((this._ser_id != value))
				{
					this.Onser_idChanging(value);
					this.SendPropertyChanging();
					this._ser_id = value;
					this.SendPropertyChanged("ser_id");
					this.Onser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ser_nombre", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ser_nombre
		{
			get
			{
				return this._ser_nombre;
			}
			set
			{
				if ((this._ser_nombre != value))
				{
					this.Onser_nombreChanging(value);
					this.SendPropertyChanging();
					this._ser_nombre = value;
					this.SendPropertyChanged("ser_nombre");
					this.Onser_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ser_precio", DbType="Decimal(8,2) NOT NULL")]
		public decimal ser_precio
		{
			get
			{
				return this._ser_precio;
			}
			set
			{
				if ((this._ser_precio != value))
				{
					this.Onser_precioChanging(value);
					this.SendPropertyChanging();
					this._ser_precio = value;
					this.SendPropertyChanged("ser_precio");
					this.Onser_precioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ser_observacion", DbType="NVarChar(200)")]
		public string ser_observacion
		{
			get
			{
				return this._ser_observacion;
			}
			set
			{
				if ((this._ser_observacion != value))
				{
					this.Onser_observacionChanging(value);
					this.SendPropertyChanging();
					this._ser_observacion = value;
					this.SendPropertyChanged("ser_observacion");
					this.Onser_observacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ser_status", DbType="Char(1) NOT NULL")]
		public char ser_status
		{
			get
			{
				return this._ser_status;
			}
			set
			{
				if ((this._ser_status != value))
				{
					this.Onser_statusChanging(value);
					this.SendPropertyChanging();
					this._ser_status = value;
					this.SendPropertyChanged("ser_status");
					this.Onser_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ser_add", DbType="DateTime NOT NULL")]
		public System.DateTime ser_add
		{
			get
			{
				return this._ser_add;
			}
			set
			{
				if ((this._ser_add != value))
				{
					this.Onser_addChanging(value);
					this.SendPropertyChanging();
					this._ser_add = value;
					this.SendPropertyChanged("ser_add");
					this.Onser_addChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SERVICIO_DETALL_SERVICIO", Storage="_DETALL_SERVICIO", ThisKey="ser_id", OtherKey="ser_id")]
		public EntitySet<DETALL_SERVICIO> DETALL_SERVICIO
		{
			get
			{
				return this._DETALL_SERVICIO;
			}
			set
			{
				this._DETALL_SERVICIO.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DETALL_SERVICIO(DETALL_SERVICIO entity)
		{
			this.SendPropertyChanging();
			entity.SERVICIO = this;
		}
		
		private void detach_DETALL_SERVICIO(DETALL_SERVICIO entity)
		{
			this.SendPropertyChanging();
			entity.SERVICIO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.USUARIO")]
	public partial class USUARIO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _usu_id;
		
		private string _usu_correo;
		
		private string _usu_password;
		
		private string _usu_apellidos;
		
		private string _usu_nombres;
		
		private char _usu_status;
		
		private System.DateTime _usu_add;
		
		private System.Nullable<int> _rol_id;
		
		private EntityRef<ROL> _ROL;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onusu_idChanging(int value);
    partial void Onusu_idChanged();
    partial void Onusu_correoChanging(string value);
    partial void Onusu_correoChanged();
    partial void Onusu_passwordChanging(string value);
    partial void Onusu_passwordChanged();
    partial void Onusu_apellidosChanging(string value);
    partial void Onusu_apellidosChanged();
    partial void Onusu_nombresChanging(string value);
    partial void Onusu_nombresChanged();
    partial void Onusu_statusChanging(char value);
    partial void Onusu_statusChanged();
    partial void Onusu_addChanging(System.DateTime value);
    partial void Onusu_addChanged();
    partial void Onrol_idChanging(System.Nullable<int> value);
    partial void Onrol_idChanged();
    #endregion
		
		public USUARIO()
		{
			this._ROL = default(EntityRef<ROL>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int usu_id
		{
			get
			{
				return this._usu_id;
			}
			set
			{
				if ((this._usu_id != value))
				{
					this.Onusu_idChanging(value);
					this.SendPropertyChanging();
					this._usu_id = value;
					this.SendPropertyChanged("usu_id");
					this.Onusu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_correo", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string usu_correo
		{
			get
			{
				return this._usu_correo;
			}
			set
			{
				if ((this._usu_correo != value))
				{
					this.Onusu_correoChanging(value);
					this.SendPropertyChanging();
					this._usu_correo = value;
					this.SendPropertyChanged("usu_correo");
					this.Onusu_correoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string usu_password
		{
			get
			{
				return this._usu_password;
			}
			set
			{
				if ((this._usu_password != value))
				{
					this.Onusu_passwordChanging(value);
					this.SendPropertyChanging();
					this._usu_password = value;
					this.SendPropertyChanged("usu_password");
					this.Onusu_passwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_apellidos", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string usu_apellidos
		{
			get
			{
				return this._usu_apellidos;
			}
			set
			{
				if ((this._usu_apellidos != value))
				{
					this.Onusu_apellidosChanging(value);
					this.SendPropertyChanging();
					this._usu_apellidos = value;
					this.SendPropertyChanged("usu_apellidos");
					this.Onusu_apellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_nombres", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string usu_nombres
		{
			get
			{
				return this._usu_nombres;
			}
			set
			{
				if ((this._usu_nombres != value))
				{
					this.Onusu_nombresChanging(value);
					this.SendPropertyChanging();
					this._usu_nombres = value;
					this.SendPropertyChanged("usu_nombres");
					this.Onusu_nombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_status", DbType="Char(1) NOT NULL")]
		public char usu_status
		{
			get
			{
				return this._usu_status;
			}
			set
			{
				if ((this._usu_status != value))
				{
					this.Onusu_statusChanging(value);
					this.SendPropertyChanging();
					this._usu_status = value;
					this.SendPropertyChanged("usu_status");
					this.Onusu_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_add", DbType="DateTime NOT NULL")]
		public System.DateTime usu_add
		{
			get
			{
				return this._usu_add;
			}
			set
			{
				if ((this._usu_add != value))
				{
					this.Onusu_addChanging(value);
					this.SendPropertyChanging();
					this._usu_add = value;
					this.SendPropertyChanged("usu_add");
					this.Onusu_addChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol_id", DbType="Int")]
		public System.Nullable<int> rol_id
		{
			get
			{
				return this._rol_id;
			}
			set
			{
				if ((this._rol_id != value))
				{
					if (this._ROL.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onrol_idChanging(value);
					this.SendPropertyChanging();
					this._rol_id = value;
					this.SendPropertyChanged("rol_id");
					this.Onrol_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ROL_USUARIO", Storage="_ROL", ThisKey="rol_id", OtherKey="rol_id", IsForeignKey=true)]
		public ROL ROL
		{
			get
			{
				return this._ROL.Entity;
			}
			set
			{
				ROL previousValue = this._ROL.Entity;
				if (((previousValue != value) 
							|| (this._ROL.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ROL.Entity = null;
						previousValue.USUARIO.Remove(this);
					}
					this._ROL.Entity = value;
					if ((value != null))
					{
						value.USUARIO.Add(this);
						this._rol_id = value.rol_id;
					}
					else
					{
						this._rol_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("ROL");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
